services:
  rdrs:
    build: .
    container_name: rdrs
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:z
      - ./logs:/app/logs:z
      - ./app:/app/app:z
    environment:
      - PYTHONUNBUFFERED=1
    restart: "no"
